version: '2'
services:
 alfresco:
  build: ./alfresco
  links:
   - share
   - httpd
   - solr4
   - libreoffice
   - cas

 db:
  build: ./postgres
  network_mode: service:alfresco
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco

 httpd:
  build: ./httpd
  ports:
   - 80:80
   - 443:443

 share:
  build: ./share
  links: 
   - cas
   - httpd

 solr4:
  build: ./solr4

 libreoffice:
  image: keensoft/libreoffice:4.4.5
  user: root
 
 cas:
  build: ./cas
  ports: 
   - 8443:8443
  links:
   - ldap

 ldap:
  build: ./openldap
  ports:
   - 389:389
   - 636:636
