version: "3"

services:
    http:
        build: ./http
        ports:
          - 80:80 #HTTP
        links:
          - alfresco
          - share
          - solr6

    alfresco:
        # image: alfresco/alfresco-content-repository-community:6.0.5-ea
        build: ./alfresco
        environment:
            JAVA_OPTS : "
                -Ddb.driver=org.postgresql.Driver
                -Ddb.username=alfresco
                -Ddb.password=alfresco
                -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
                -Dsolr.host=solr6
                -Dsolr.port=8983
                -Dsolr.secureComms=none
                -Dsolr.base.url=/solr
                -Dindex.subsystem.name=solr6
                -Ddeployment.method=DOCKER_COMPOSE
                "
        volumes:
          - ./data/alf-repo-data:/usr/local/tomcat/alf_data
        ports:
          - 21:2121   #FTP port
          - 25:2525   #SMTP port
          - 143:1143  #IMAP port
#          - 445:1145      #CIFS
#          - 137:1137/udp  #CIFS
#          - 138:1138/udp  #CIFS
#          - 139:1139      #CIFS

    share:
        # image: alfresco/alfresco-share:6.0.a
        build: ./share
        environment:
            - REPO_HOST=alfresco
            - REPO_PORT=8080

    postgres:
        image: postgres:10.1
        environment:
            - POSTGRES_PASSWORD=alfresco
            - POSTGRES_USER=alfresco
            - POSTGRES_DB=alfresco
        command: postgres -c max_connections=300 -c log_min_messages=LOG
        volumes:
           - ./data/postgres-data:/var/lib/postgresql/data
        ports:
            - 5432:5432

    solr6:
        image: alfresco/alfresco-search-services:1.1.1
        environment:
            #Solr needs to know how to register itself with Alfresco
            - SOLR_ALFRESCO_HOST=alfresco
            - SOLR_ALFRESCO_PORT=8080
            #Alfresco needs to know how to call solr
            - SOLR_SOLR_HOST=solr6
            - SOLR_SOLR_PORT=8983
            #Create the default alfresco and archive cores
            - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
        volumes:
          - ./data/solr-data:/opt/alfresco-search-services/data